security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\UserAuthenticator
            logout:
                path: app_logout

    access_control:
          - { path: ^/admin, roles: ROLE_ADMIN }
          - { path: ^/admin/edition, roles: ROLE_OPERATOR }
          - { path: ^/profil, roles: ROLE_PUBLIC }

    role_hierarchy:
        ROLE_ADMIN: ROLE_OPERATOR
        ### TODO restreindre les possibilitées de faire un emprunt pour l'opérateur ###
        ROLE_OPERATOR: ROLE_AUDAP_MEMBER
        ROLE_AUDAP_MEMBER: ROLE_AUDAP_PARTNER
        ROLE_AUDAP_PARTNER: ROLE_PUBLIC

